# Общий SwiftLint конфиг

line_length:
  warning: 100
  error: 120
  ignores_comments: true

type_name:
  max_length: 60
  allowed_symbols:
    - _
  excluded:
    - ID
    - S # Typealias S for State from Store

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 5
  error: 999
  ignores_default_parameters: false

large_tuple:
  warning: 2
  error: 999

cyclomatic_complexity:
  warning: 12
  error: 999
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3

identifier_name:
  excluded:
    - ad
    - at
    - by
    - db
    - di
    - dx
    - dy
    - i
    - id
    - j
    - no
    - ok
    - on
    - op
    - pk
    - to
    - ui
    - vc
    - vm
    - x
    - y
    - isRequestForNotificationInContextEligible
  allowed_symbols:
    - _

trailing_closure:
  severity: error
  only_single_muted_parameter: true

enum_case_associated_values_count:
  warning: 5
  error: 999

todo:
  only: FIXME

empty_count:
  severity: error
  only_after_dot: true

empty_string:
  severity: error

explicit_init:
  severity: error

force_unwrapping:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_type_annotation:
  severity: error

redundant_self_in_closure:
  severity: error

unavailable_function:
  severity: error

unused_optional_binding:
  severity: error


empty_collection_literal:
  severity: error

direct_return:
  severity: error

convenience_type:
  severity: error

contains_over_filter_is_empty:
  severity: error

contains_over_first_not_nil:
  severity: error

contains_over_filter_count:
  severity: error

opt_in_rules:
  - explicit_init
  - force_unwrapping
  - first_where
  - last_where
  - private_swiftui_state
  - unowned_variable_capture
  - xct_specific_matcher
  - unavailable_function
  - trailing_closure
  - toggle_bool
  - single_test_class
  - return_value_from_void_function
  - redundant_type_annotation
  - redundant_self_in_closure
  - redundant_nil_coalescing
  - prohibited_super_call
  - prefer_self_type_over_type_of_self
  - overridden_super_call
  - optional_enum_case_matching
  - multiline_function_chains
  - let_var_whitespace
  - file_name_no_space
  - fallthrough
  - enum_case_associated_values_count
  - empty_xctest_method
  - empty_string
  - empty_count
  - empty_collection_literal
  - direct_return
  - convenience_type
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_filter_count

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - control_statement
  - multiple_closures_with_trailing_closure
  - switch_case_alignment
  - inclusive_language
  - orphaned_doc_comment
  - for_where
  - file_length
  - type_body_length
  - private_over_fileprivate
  - weak_delegate
  - class_delegate_protocol
  - trailing_comma
  - blanket_disable_command
  - redundant_optional_initialization
